### ISSUE TITLE
deploy to 1-n commit

### ISSUE THREAD

**Issue by Arhell** [peaceiris/actions-gh-pages#575]
There is an option to collapse everything into 1-n commit?
In other words, when we go to the deployment, then everything is connected to 1-n commit only in the deployment branch.

example
`git checkout -b deploy`
`git reset --soft HEAD~$(git rev-list --count HEAD ^master`
`git add -A`
`git commit -m "deploy"`
`git push -f origin deploy:master`

So that commits do not accumulate in the deployment branch, but there is 1-n, the last

**Comment by peaceiris** [comment]
Today (v3), this action supports the `force_orphan` option to keep only the last commit on a publishing branch. (This will be renamed with `keep_history` #352) There is no way to squash all commits into 1-n commits but maybe you can [create a Git tag on a publishing branch](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-git-tag) instead. Therefore, using `force_orphan` and `tag_name` options can implement what you want. Since we can reproduce the deployment assets from a source branch, I have no plan to add a 1-n commits option now.
