### ISSUE TITLE
support: New release?

### ISSUE THREAD

**Issue by polarathene** [peaceiris/actions-gh-pages#685]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

The Actions marketplace lists the latest version as 3.7.3 (Oct 2020 release), and the Github project releases page shows 3.8.0 (Mar 2021) as the latest release.

I see there's been a buch of commits, notably maintenance ones that update dependencies. Any reason no new releases are being put out that make these available?

---

Thanks for the great action btw! :)

Feedback for this issue form, while I understand "Relevant links" would be useful for troubleshooting, it seems unnecessary for "Relevant log output" and especially "Additional context" fields to be required inputs, you may want to make those optional.

### Relevant links

```markdown
N/A
```

### Relevant log output

N/A

### Additional context.

N/A

**Comment by peaceiris** [comment]
Thank you for your concern.

> I see there's been a much of commits, notably maintenance ones that update dependencies. Any reason no new releases are being put out that make these available?

Yes, generally, We need to increase dependency versions and release those continuously to apply bug/security fixes. In recent days of this project, all of them are devDependencies, not critical dependencies, they do not affect the use of end-users and core features of this action. In addition, since I am working on [the next major version](https://github.com/peaceiris/actions-gh-pages/milestone/1) and refactoring these days, I thought that I had wanted to release them as the next major version.

But, this issue is a good time to release some of them, I will ship them as v3.9.0 with some small new features. 👍

**Comment by peaceiris** [comment]
> Feedback for this issue form, while I understand "Relevant links" would be useful for troubleshooting, it seems unnecessary for "Relevant log output" and especially "Additional context" fields to be required inputs, you may want to make those optional.

Exactly. Thank you! Done by https://github.com/peaceiris/actions-gh-pages/commit/e8cba386c2fbcf55a8eeca1302315b6b41bb7fe9

**Comment by peaceiris** [comment]
[The milestone of v3.9.0](https://github.com/peaceiris/actions-gh-pages/milestone/2) has been created.

**Comment by polarathene** [comment]
> In recent days of this project, all of them are devDependencies, not critical dependencies, they do not affect the use of end-users and core features of this action.

Awesome thanks! I didn't look too deeply to consider if the dep updates were dev dependencies, whoops! :sweat_smile:
